<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Brand;
use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $brands = Brand::pluck('id')->toArray();
        $categories = Category::where('type', 'product')->pluck('id')->toArray();

        $products = [
            [
                'name' => 'Standard 20ft Dry Container',
                'slug' => 'standard-20ft-dry-container',
                'type' => 'physical',
                'description' => 'High-quality 20-foot dry shipping container suitable for general cargo transportation. Made with corrosion-resistant steel and features secure locking mechanisms.',
                'short_description' => '20ft standard dry container for general cargo',
                'sku' => 'CONT-20FT-STD-001',
                'price' => 25000000,
                'compare_at_price' => 28000000,
                'cost_per_item' => 20000000,
                'track_quantity' => true,
                'quantity' => 15,
                'barcode' => '8901234567890',
                'status' => 'published',
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new' => false,
                'show_price' => true,
                'published_at' => now(),
                'position' => 1,
                'meta_title' => 'Standard 20ft Dry Container - Quality Shipping Solution',
                'meta_description' => 'Premium 20ft dry container for secure cargo transportation. Competitive pricing and immediate availability.',
                'tags' => ['20ft', 'dry', 'standard', 'shipping', 'cargo']
            ],
            [
                'name' => 'Standard 40ft Dry Container',
                'slug' => 'standard-40ft-dry-container',
                'type' => 'physical',
                'description' => 'Spacious 40-foot dry shipping container perfect for large-volume cargo transportation. Features reinforced flooring and weatherproof construction.',
                'short_description' => '40ft standard dry container for large cargo',
                'sku' => 'CONT-40FT-STD-002',
                'price' => 35000000,
                'compare_at_price' => 40000000,
                'cost_per_item' => 28000000,
                'track_quantity' => true,
                'quantity' => 10,
                'barcode' => '8901234567891',
                'status' => 'published',
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new' => false,
                'show_price' => true,
                'published_at' => now(),
                'position' => 2,
                'meta_title' => 'Standard 40ft Dry Container - Large Capacity Shipping',
                'meta_description' => 'Spacious 40ft dry container for bulk cargo. Durable construction and competitive pricing.',
                'tags' => ['40ft', 'dry', 'standard', 'shipping', 'cargo', 'large']
            ],
            [
                'name' => '40ft High Cube Container',
                'slug' => '40ft-high-cube-container',
                'type' => 'physical',
                'description' => 'Extra tall 40-foot high cube container providing additional foot of height for oversized cargo. Ideal for light, bulky items.',
                'short_description' => '40ft high cube container with extra height',
                'sku' => 'CONT-40FT-HC-003',
                'price' => 38000000,
                'compare_at_price' => 42000000,
                'cost_per_item' => 30000000,
                'track_quantity' => true,
                'quantity' => 8,
                'barcode' => '8901234567892',
                'status' => 'published',
                'is_featured' => false,
                'is_bestseller' => true,
                'is_new' => false,
                'show_price' => true,
                'published_at' => now(),
                'position' => 3,
                'meta_title' => '40ft High Cube Container - Extra Height Capacity',
                'meta_description' => '40ft high cube container with one foot extra height. Perfect for oversized cargo.',
                'tags' => ['40ft', 'high-cube', 'extra-height', 'shipping', 'cargo']
            ],
            [
                'name' => '20ft Refrigerated Container',
                'slug' => '20ft-refrigerated-container',
                'type' => 'physical',
                'description' => 'Temperature-controlled 20-foot refrigerated container for perishable goods. Maintains consistent temperature from -25°C to +25°C.',
                'short_description' => '20ft refrigerated container for temperature-sensitive cargo',
                'sku' => 'CONT-20FT-REF-004',
                'price' => 45000000,
                'compare_at_price' => 50000000,
                'cost_per_item' => 36000000,
                'track_quantity' => true,
                'quantity' => 5,
                'barcode' => '8901234567893',
                'status' => 'published',
                'is_featured' => true,
                'is_bestseller' => false,
                'is_new' => true,
                'show_price' => true,
                'published_at' => now(),
                'position' => 4,
                'meta_title' => '20ft Refrigerated Container - Temperature Control',
                'meta_description' => '20ft refrigerated container with precise temperature control for perishable goods.',
                'tags' => ['20ft', 'refrigerated', 'temperature-controlled', 'cold-chain', 'perishable']
            ],
            [
                'name' => '40ft Refrigerated Container',
                'slug' => '40ft-refrigerated-container',
                'type' => 'physical',
                'description' => 'Large capacity 40-foot refrigerated container for bulk temperature-sensitive cargo. Advanced cooling system with remote monitoring.',
                'short_description' => '40ft refrigerated container for bulk cold storage',
                'sku' => 'CONT-40FT-REF-005',
                'price' => 65000000,
                'compare_at_price' => 70000000,
                'cost_per_item' => 52000000,
                'track_quantity' => true,
                'quantity' => 3,
                'barcode' => '8901234567894',
                'status' => 'published',
                'is_featured' => false,
                'is_bestseller' => false,
                'is_new' => true,
                'show_price' => true,
                'published_at' => now(),
                'position' => 5,
                'meta_title' => '40ft Refrigerated Container - Large Cold Storage',
                'meta_description' => '40ft refrigerated container with advanced cooling system for bulk perishable goods.',
                'tags' => ['40ft', 'refrigerated', 'temperature-controlled', 'cold-chain', 'bulk']
            ],
            [
                'name' => '20ft Open Top Container',
                'slug' => '20ft-open-top-container',
                'type' => 'physical',
                'description' => '20-foot open top container with removable tarpaulin roof for easy loading of oversized cargo from above.',
                'short_description' => '20ft open top container for top-loading cargo',
                'sku' => 'CONT-20FT-OT-006',
                'price' => 32000000,
                'compare_at_price' => 35000000,
                'cost_per_item' => 25000000,
                'track_quantity' => true,
                'quantity' => 6,
                'barcode' => '8901234567895',
                'status' => 'published',
                'is_featured' => false,
                'is_bestseller' => false,
                'is_new' => false,
                'show_price' => true,
                'published_at' => now(),
                'position' => 6,
                'meta_title' => '20ft Open Top Container - Top Loading Solution',
                'meta_description' => '20ft open top container with removable roof for easy oversized cargo loading.',
                'tags' => ['20ft', 'open-top', 'oversized', 'top-loading', 'cargo']
            ],
            [
                'name' => '40ft Flat Rack Container',
                'slug' => '40ft-flat-rack-container',
                'type' => 'physical',
                'description' => '40-foot flat rack container with collapsible sides for transporting heavy machinery and oversized equipment.',
                'short_description' => '40ft flat rack container for heavy machinery',
                'sku' => 'CONT-40FT-FR-007',
                'price' => 40000000,
                'compare_at_price' => 45000000,
                'cost_per_item' => 32000000,
                'track_quantity' => true,
                'quantity' => 4,
                'barcode' => '8901234567896',
                'status' => 'published',
                'is_featured' => false,
                'is_bestseller' => false,
                'is_new' => false,
                'show_price' => true,
                'published_at' => now(),
                'position' => 7,
                'meta_title' => '40ft Flat Rack Container - Heavy Equipment Transport',
                'meta_description' => '40ft flat rack container with collapsible sides for heavy machinery transport.',
                'tags' => ['40ft', 'flat-rack', 'heavy-machinery', 'oversized', 'equipment']
            ],
            [
                'name' => '20ft Tank Container',
                'slug' => '20ft-tank-container',
                'type' => 'physical',
                'description' => '20-foot tank container for transporting liquid bulk materials. Features stainless steel construction and safety valves.',
                'short_description' => '20ft tank container for liquid transport',
                'sku' => 'CONT-20FT-TANK-008',
                'price' => 55000000,
                'compare_at_price' => 60000000,
                'cost_per_item' => 44000000,
                'track_quantity' => true,
                'quantity' => 7,
                'barcode' => '8901234567897',
                'status' => 'published',
                'is_featured' => true,
                'is_bestseller' => false,
                'is_new' => false,
                'show_price' => true,
                'published_at' => now(),
                'position' => 8,
                'meta_title' => '20ft Tank Container - Liquid Transport Solution',
                'meta_description' => '20ft stainless steel tank container for safe liquid bulk transportation.',
                'tags' => ['20ft', 'tank', 'liquid', 'bulk', 'stainless-steel']
            ],
            [
                'name' => '20ft Ventilated Container',
                'slug' => '20ft-ventilated-container',
                'type' => 'physical',
                'description' => '20-foot ventilated container with natural ventilation system for agricultural products requiring air circulation.',
                'short_description' => '20ft ventilated container for agricultural products',
                'sku' => 'CONT-20FT-VENT-009',
                'price' => 28000000,
                'compare_at_price' => 31000000,
                'cost_per_item' => 22000000,
                'track_quantity' => true,
                'quantity' => 9,
                'barcode' => '8901234567898',
                'status' => 'published',
                'is_featured' => false,
                'is_bestseller' => false,
                'is_new' => false,
                'show_price' => true,
                'published_at' => now(),
                'position' => 9,
                'meta_title' => '20ft Ventilated Container - Agricultural Transport',
                'meta_description' => '20ft ventilated container with natural airflow for fresh produce transport.',
                'tags' => ['20ft', 'ventilated', 'agricultural', 'air-circulation', 'fresh-produce']
            ],
            [
                'name' => 'Container Office 20ft',
                'slug' => 'container-office-20ft',
                'type' => 'physical',
                'description' => 'Converted 20-foot container into functional office space with insulation, windows, doors, and electrical installation.',
                'short_description' => '20ft container converted to office space',
                'sku' => 'CONT-20FT-OFF-010',
                'price' => 45000000,
                'compare_at_price' => 50000000,
                'cost_per_item' => 35000000,
                'track_quantity' => true,
                'quantity' => 12,
                'barcode' => '8901234567899',
                'status' => 'published',
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new' => false,
                'show_price' => true,
                'published_at' => now(),
                'position' => 10,
                'meta_title' => 'Container Office 20ft - Mobile Office Solution',
                'meta_description' => '20ft container converted to fully functional office space with modern amenities.',
                'tags' => ['20ft', 'office', 'converted', 'mobile', 'workspace']
            ],
            [
                'name' => 'Container Cafe 20ft',
                'slug' => 'container-cafe-20ft',
                'type' => 'physical',
                'description' => 'Stylish 20-foot container converted into modern cafe with serving counter, seating area, and kitchen facilities.',
                'short_description' => '20ft container converted to cafe',
                'sku' => 'CONT-20FT-CAFE-011',
                'price' => 52000000,
                'compare_at_price' => 58000000,
                'cost_per_item' => 40000000,
                'track_quantity' => true,
                'quantity' => 5,
                'barcode' => '8901234567900',
                'status' => 'published',
                'is_featured' => false,
                'is_bestseller' => false,
                'is_new' => true,
                'show_price' => true,
                'published_at' => now(),
                'position' => 11,
                'meta_title' => 'Container Cafe 20ft - Mobile Coffee Shop',
                'meta_description' => '20ft container converted to modern cafe with complete kitchen facilities.',
                'tags' => ['20ft', 'cafe', 'coffee-shop', 'converted', 'food-business']
            ],
            [
                'name' => 'Container Shop 20ft',
                'slug' => 'container-shop-20ft',
                'type' => 'physical',
                'description' => '20-foot container converted into retail shop space with glass storefront, storage area, and customer service counter.',
                'short_description' => '20ft container converted to retail shop',
                'sku' => 'CONT-20FT-SHOP-012',
                'price' => 48000000,
                'compare_at_price' => 53000000,
                'cost_per_item' => 38000000,
                'track_quantity' => true,
                'quantity' => 8,
                'barcode' => '8901234567901',
                'status' => 'published',
                'is_featured' => false,
                'is_bestseller' => false,
                'is_new' => false,
                'show_price' => true,
                'published_at' => now(),
                'position' => 12,
                'meta_title' => 'Container Shop 20ft - Retail Business Solution',
                'meta_description' => '20ft container converted to modern retail shop with glass storefront.',
                'tags' => ['20ft', 'shop', 'retail', 'converted', 'business']
            ],
            [
                'name' => 'Container House 40ft',
                'slug' => 'container-house-40ft',
                'type' => 'physical',
                'description' => 'Spacious 40-foot container converted into comfortable living space with bedroom, bathroom, kitchen, and living area.',
                'short_description' => '40ft container converted to living space',
                'sku' => 'CONT-40FT-HOUSE-013',
                'price' => 85000000,
                'compare_at_price' => 95000000,
                'cost_per_item' => 68000000,
                'track_quantity' => true,
                'quantity' => 3,
                'barcode' => '8901234567902',
                'status' => 'published',
                'is_featured' => true,
                'is_bestseller' => false,
                'is_new' => true,
                'show_price' => true,
                'published_at' => now(),
                'position' => 13,
                'meta_title' => 'Container House 40ft - Modern Living Solution',
                'meta_description' => '40ft container converted to comfortable home with complete living facilities.',
                'tags' => ['40ft', 'house', 'living', 'converted', 'residential']
            ],
            [
                'name' => 'Container Toilet 20ft',
                'slug' => 'container-toilet-20ft',
                'type' => 'physical',
                'description' => '20-foot container converted into public toilet facility with multiple stalls, hand washing stations, and waste management system.',
                'short_description' => '20ft container converted to public toilet facility',
                'sku' => 'CONT-20FT-TOILET-014',
                'price' => 35000000,
                'compare_at_price' => 39000000,
                'cost_per_item' => 28000000,
                'track_quantity' => true,
                'quantity' => 10,
                'barcode' => '8901234567903',
                'status' => 'published',
                'is_featured' => false,
                'is_bestseller' => false,
                'is_new' => false,
                'show_price' => true,
                'published_at' => now(),
                'position' => 14,
                'meta_title' => 'Container Toilet 20ft - Public Facility Solution',
                'meta_description' => '20ft container converted to modern public toilet with complete facilities.',
                'tags' => ['20ft', 'toilet', 'public-facility', 'converted', 'sanitation']
            ],
            [
                'name' => 'Security Post Container 20ft',
                'slug' => 'security-post-container-20ft',
                'type' => 'physical',
                'description' => '20-foot container converted into security post with observation windows, communication equipment, and monitoring systems.',
                'short_description' => '20ft container converted to security post',
                'sku' => 'CONT-20FT-SECURITY-015',
                'price' => 32000000,
                'compare_at_price' => 36000000,
                'cost_per_item' => 25000000,
                'track_quantity' => true,
                'quantity' => 15,
                'barcode' => '8901234567904',
                'status' => 'published',
                'is_featured' => false,
                'is_bestseller' => false,
                'is_new' => false,
                'show_price' => true,
                'published_at' => now(),
                'position' => 15,
                'meta_title' => 'Security Post Container 20ft - Guard Station',
                'meta_description' => '20ft container converted to secure security post with monitoring capabilities.',
                'tags' => ['20ft', 'security', 'guard-post', 'converted', 'monitoring']
            ],
            [
                'name' => 'Double Door 20ft Container',
                'slug' => 'double-door-20ft-container',
                'type' => 'physical',
                'description' => '20-foot container with double doors on both ends for easy loading and unloading from either side.',
                'short_description' => '20ft container with double doors on both ends',
                'sku' => 'CONT-20FT-DD-016',
                'price' => 27000000,
                'compare_at_price' => 30000000,
                'cost_per_item' => 21000000,
                'track_quantity' => true,
                'quantity' => 11,
                'barcode' => '8901234567905',
                'status' => 'published',
                'is_featured' => false,
                'is_bestseller' => false,
                'is_new' => false,
                'show_price' => true,
                'published_at' => now(),
                'position' => 16,
                'meta_title' => 'Double Door 20ft Container - Easy Access Loading',
                'meta_description' => '20ft container with double doors on both ends for convenient cargo access.',
                'tags' => ['20ft', 'double-door', 'easy-access', 'loading', 'shipping']
            ],
            [
                'name' => 'Insulated 20ft Container',
                'slug' => 'insulated-20ft-container',
                'type' => 'physical',
                'description' => '20-foot insulated container with thermal protection for temperature-sensitive cargo that doesn\'t require active refrigeration.',
                'short_description' => '20ft insulated container for thermal protection',
                'sku' => 'CONT-20FT-INSUL-017',
                'price' => 30000000,
                'compare_at_price' => 33000000,
                'cost_per_item' => 24000000,
                'track_quantity' => true,
                'quantity' => 7,
                'barcode' => '8901234567906',
                'status' => 'published',
                'is_featured' => false,
                'is_bestseller' => false,
                'is_new' => false,
                'show_price' => true,
                'published_at' => now(),
                'position' => 17,
                'meta_title' => 'Insulated 20ft Container - Thermal Protection',
                'meta_description' => '20ft insulated container providing thermal protection for temperature-sensitive cargo.',
                'tags' => ['20ft', 'insulated', 'thermal', 'temperature-protection', 'cargo']
            ],
            [
                'name' => 'Side Door 40ft Container',
                'slug' => 'side-door-40ft-container',
                'type' => 'physical',
                'description' => '40-foot container with side door access for easy loading of palletized cargo and bulky items.',
                'short_description' => '40ft container with side door access',
                'sku' => 'CONT-40FT-SD-018',
                'price' => 42000000,
                'compare_at_price' => 46000000,
                'cost_per_item' => 33000000,
                'track_quantity' => true,
                'quantity' => 5,
                'barcode' => '8901234567907',
                'status' => 'published',
                'is_featured' => false,
                'is_bestseller' => false,
                'is_new' => false,
                'show_price' => true,
                'published_at' => now(),
                'position' => 18,
                'meta_title' => 'Side Door 40ft Container - Convenient Side Access',
                'meta_description' => '40ft container with side door for easy loading of palletized and bulky cargo.',
                'tags' => ['40ft', 'side-door', 'pallet-access', 'loading', 'convenient']
            ],
            [
                'name' => 'Container Workshop 20ft',
                'slug' => 'container-workshop-20ft',
                'type' => 'physical',
                'description' => '20-foot container converted into functional workshop with workbenches, tool storage, and electrical installation.',
                'short_description' => '20ft container converted to workshop space',
                'sku' => 'CONT-20FT-WORKSHOP-019',
                'price' => 41000000,
                'compare_at_price' => 45000000,
                'cost_per_item' => 32000000,
                'track_quantity' => true,
                'quantity' => 6,
                'barcode' => '8901234567908',
                'status' => 'published',
                'is_featured' => false,
                'is_bestseller' => false,
                'is_new' => true,
                'show_price' => true,
                'published_at' => now(),
                'position' => 19,
                'meta_title' => 'Container Workshop 20ft - Mobile Workshop',
                'meta_description' => '20ft container converted to fully equipped workshop with tool storage.',
                'tags' => ['20ft', 'workshop', 'tools', 'converted', 'mobile-workspace']
            ],
            [
                'name' => 'Container Storage 20ft',
                'slug' => 'container-storage-20ft',
                'type' => 'physical',
                'description' => 'Secure 20-foot container optimized for storage purposes with enhanced security features and weatherproofing.',
                'short_description' => '20ft container optimized for secure storage',
                'sku' => 'CONT-20FT-STORAGE-020',
                'price' => 24000000,
                'compare_at_price' => 27000000,
                'cost_per_item' => 19000000,
                'track_quantity' => true,
                'quantity' => 20,
                'barcode' => '8901234567909',
                'status' => 'published',
                'is_featured' => false,
                'is_bestseller' => true,
                'is_new' => false,
                'show_price' => true,
                'published_at' => now(),
                'position' => 20,
                'meta_title' => 'Container Storage 20ft - Secure Storage Solution',
                'meta_description' => '20ft container with enhanced security features for safe storage.',
                'tags' => ['20ft', 'storage', 'secure', 'weatherproof', 'safety']
            ]
        ];

        foreach ($products as $index => $productData) {
            // Assign random brand and category
            $productData['brand_id'] = $brands[array_rand($brands)];
            $productData['category_id'] = $categories[array_rand($categories)];
            
            Product::create($productData);
        }
    }
}
